# Generated by Django 3.2.6 on 2021-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('profile_picture', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
