# Generated by Django 3.2.6 on 2021-08-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0002_expertise_collegiates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegiate',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstituteName', models.CharField(max_length=200)),
                ('InstituteAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('collegiates', models.ManyToManyField(to='schrest.Collegiate')),
            ],
        ),
    ]
