# Generated by Django 3.2.6 on 2021-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0003_auto_20210809_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='collegiates',
            field=models.ManyToManyField(blank=True, to='schrest.Collegiate'),
        ),
    ]
