# Generated by Django 3.2.6 on 2021-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0004_alter_expertise_collegiates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=200)),
                ('link_title', models.CharField(blank=True, max_length=200, null=True)),
                ('link_icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collegiate',
            name='links',
            field=models.ManyToManyField(blank=True, to='schrest.Link'),
        ),
    ]
