# Generated by Django 3.2.6 on 2021-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0005_auto_20210809_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_title', models.CharField(blank=True, max_length=200, null=True)),
                ('laboratory_icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collegiate',
            name='laboratories',
            field=models.ManyToManyField(to='schrest.Laboratory'),
        ),
        migrations.AddField(
            model_name='institute',
            name='laboratories',
            field=models.ManyToManyField(to='schrest.Laboratory'),
        ),
    ]
