# Generated by Django 3.2.6 on 2021-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0006_auto_20210810_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegiate',
            name='laboratories',
            field=models.ManyToManyField(blank=True, to='schrest.Laboratory'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='collegiates',
            field=models.ManyToManyField(blank=True, to='schrest.Collegiate'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='laboratories',
            field=models.ManyToManyField(blank=True, to='schrest.Laboratory'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.TextField(),
        ),
    ]
