# Generated by Django 3.2.6 on 2021-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0008_auto_20210812_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laberatories'},
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='InstituteName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
