# Generated by Django 3.2.6 on 2021-08-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0009_auto_20210812_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
