# Generated by Django 3.2.6 on 2021-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0010_alter_expertise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegiate',
            name='educations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collegiate',
            name='main_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegiate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
