# Generated by Django 3.2.6 on 2021-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0011_auto_20210813_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegiate',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
