# Generated by Django 3.2.6 on 2021-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrest', '0012_alter_collegiate_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegiate',
            name='profile_picture',
            field=models.URLField(blank=True, default='/images/scholar.png', null=True),
        ),
    ]
